# Generated by Django 3.2.3 on 2021-09-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'verbose_name': 'Воспитанник', 'verbose_name_plural': 'Воспитанника'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Представитель детского дома', 'verbose_name_plural': 'Воспитанника'},
        ),
        migrations.AddField(
            model_name='children',
            name='age',
            field=models.CharField(default=False, max_length=99, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='children',
            name='children_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_children', to='authentication.director'),
        ),
        migrations.AddField(
            model_name='children',
            name='city',
            field=models.CharField(default=False, max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='children',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='children',
            name='sex',
            field=models.CharField(default=False, max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Адрес'),
        ),
    ]
